### PR TITLE
add post-to-confidence

### PR DESCRIPTION
**Pull request by naxingyu**
Add post-to-confidence for reproducing Guoguo's small KWS on ICASSP 2014.
@chenguoguo do you have time to have a look at this?

### CODE REVIEW

**Comment by chenguoguo** [comment]
here:

```
+      const int32 frames = post.NumRows();
+      const int32 labels = post.NumCols();
```

I guess frames and labels don't change across the table? If yes you can throw them out of the loop.

here:

```
+          for (int32 k = h_smooth; k <= j; k++)
+            sum += post(k, i);
```

You can probably make it more efficient by dropping the loop and keep a sum of a window of frames.

BTW how did you train your net? Did you use manually designed special keyword labels? Also please keep me updated if you are testing it :-)

**Comment by naxingyu** [comment]
Thanks for the review :-)

在 2016/8/5 23:37, Guoguo Chen 写道:

**Comment by chenguoguo** [comment]
“I wonder how didn't make the deteced decision using this” I don't fully get your point here, you meant making a decision using what?

Also, did you use CMVN of any kind?

**Comment by naxingyu** [comment]
For example, I have the confidence curve of a test sentence as below.

How do I decide whether the keyword is detected or not? I am using CMN.

在 2016/8/8 13:04, Guoguo Chen 写道:

**Comment by chenguoguo** [comment]
Looks like the attachment didn't go through -- github probably doesn't
allow it.

Guoguo

**Pull request merged**
